### ISSUE TITLE
Testing packages installations for multiple operating systems.

### ISSUE THREAD

**Issue by priyankt68** [priyankt68/pycon_requirements#3]
- [x] 1. MacOS
- [ ] 2. Linux
- [ ] 3. Window

**Comment by shashankaryan** [comment]
I am doing it for Linux.

**Comment by dotgourav** [comment]
I tried it on Windows and in short Windows is trouble.

1. The structure script gives error on Windows with Python2. 

```
Traceback (most recent call last):
  File "src/structure.py", line 39, in <module>
    make_directory('./requirements/{}s/{}'.format(event_type, title))
  File "src/structure.py", line 8, in make_directory
    os.makedirs(directory_name)
  File "F:\Workspace\Open Source & Volunteering\Pycon India\2017\Workshops\test\venv\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 267] The directory name is invalid: './requirements/talks/Getting_Started_with_Embedded_Python:_MicroPython_and_CircuitPython'

```

2. After downloading the structured folder, I tried the fetch_requirements. It downloaded requirements for NetworkX talk. But when it came to the Tensorflow talk, it crashed and burned.
    - Tensorflow on windows is only available for Python 3.5.x(I have 2.x and 3.4.x on my system)
    -  Scipy build gave error (Traceback: https://pastebin.com/LLcjeHER)
    - Since scipy build gave error, pip install did not work either for the rest of the packages which got downloaded like Keras, pandas

3. I think I have jotted down all the points that I came across and I do think it would work for most part on windows unless there is package in requirements.txt that is not directly accessible through pip. In that case, it won't work like it happened with tensorflow.
